main:
  - name: Sobre mi
    url: /ca/#about
    weight: 10
  - name: Experi√®ncia
    url: /ca/#experience
    weight: 20
  - name: Habilitats
    url: /ca/#skills
    weight: 30
  - name: Bloc
    url: /post/
    weight: 40
  - name: Contacte
    url: /ca/contacte/
    weight: 50

footer:
  - name: Privacitat
    url: /ca/privacitat/
    weight: 10
