main:
  - name: Sobre m√≠
    url: "/#about"
    weight: 10
  - name: Experiencia
    url: "/#experience"
    weight: 20
  - name: Habilidades
    url: "/#skills"
    weight: 30
  - name: Blog
    url: /post/
    weight: 40
  - name: Contacto
    url: /contacto/
    weight: 50

footer:
  - name: Privacidad
    url: /privacidad/
    weight: 10
