main:
  - name: About
    url: /en/#about
    weight: 10
  - name: Experience
    url: /en/#experience
    weight: 20
  - name: Skills
    url: /en/#skills
    weight: 30
  - name: Blog
    url: /post/
    weight: 40
  - name: Contact
    url: /en/contact/
    weight: 50

footer:
  - name: Privacy
    url: /en/privacy/
    weight: 10
